### ISSUE TITLE
Can't load any SVG file

### ISSUE THREAD

**Issue by NedNet29** [sozi-projects/Sozi#514]
### Summary of your problem or feature request

Can't start working on Win10, Sozi doesn't load any SVG file

### Version of Sozi and other relevant software

versions :
- release 20.05
- release 21.02
- pre-release 21.04

OS : win 10 64 pro 20H2 (Windows Feature Experience Pack 120.2212.551.0)

### Steps to reproduce the problem

Download a Sozi.....windows-x64.zip , unzip, launch Sozi and try to load the very first SVG
Tried with several SVGs, including "first-presentation.svg" from Sozi website

### Expected behavior
SVG loaded

### Observed behavior

Nothing seems to happen, Sozi still shows "load svg" button on stage

### Hints and solutions (optional)
Looking at console (F12) I can see the following error : 
`C:\Users\Ned\Documents\Sozi-21.02.21-1613918986-windows-x64\resources\app\js\backend\Electron.js:216 Uncaught ReferenceError: _ is not defined`
`at C:\Users\Ned\Documents\Sozi-21.02.21-1613918986-windows-x64\resources\app\js\backend\Electron.js:216`
`at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61)`

**Comment by aumouvantsillage** [comment]
This is actually a bug. Here is an explanation:

Usually, Sozi can be notified when an SVG file changes, so that it can reload it automatically.
It did not work in your case, for some reason yet to be determined.
In that situation, Sozi was supposed to show a warning message, but there was an error that prevented it and broke the loading process.

This is fixed in Sozi 21.04.30.

When you try it, you are likely to see a warning message "This file will not be reloaded on change", but everything else should work as expected.

**Comment by NedNet29** [comment]
Hi, 
I confirm all what you wrote : it 21.04.30 version loads the svg file, and I do get the warning.
FYI, the file was located on network folder, and when I moved it to a local drive I didn't get the warning anymore.
Thank you very much for being so reactive.
