### ISSUE TITLE
Add notes or description to each frame and frame list panel

### ISSUE THREAD

**Issue by antlosolutions** [sozi-projects/Sozi#523]
Is there any easy option to add some custom text to each frame? I want to explain a little some frames and it would be nice if I can add the text in the editor and the text is shown in some place of the player.

Also, there is a way to show the frame list panel at loading?

Thanks

**Comment by NedNet29** [comment]
Hi, 

it depends on what you call "easy". 
AFAIK, the way to do this is to use layers in Inkscape : your texts would be on a different layer than the picture. and each can be set differently for each frame (including opacity, wich is really cool to make disappear the texts you don't want to see at a given frame)
see https://sozi.baierouge.fr/pages/tutorial-layers.html for more info about using layers with Sozi and Inkscape.

**Comment by aumouvantsillage** [comment]
As @NedNet29 explained, adding visual content to the presentation must be done in an SVG editor such as Inkscape.
This is by design in Sozi: the purpose of the presentation editor is to organize the presentation.

If you want to edit *presentation notes* that are not visible to the audience, Sozi provides a text box in the write pane. Presentation notes are displayed in the presenter's window when opening the document named `my-presentation-presenter.sozi.html`.

> Also, there is a way to show the frame list panel at loading?

Not at the moment. There is an old feature request with a related purpose #123
