### ISSUE TITLE
Unwanted padding/margin in the generated html

### ISSUE THREAD

**Issue by sina-mansour** [sozi-projects/Sozi#529]
### Summary of your problem or feature request

I'm using Sozi on ubuntu and create 16:9 presentations. The created HTML slideshows always have a slight margin/padding on the left and top parts. I've tried to inspect the HTML to figure out the source of this unwanted padding but wasn't able to locate it. This makes the full-screen presentations shifted to the right and down. Hence, a tiny bit of the slide is not visible.

### Version of Sozi and other relevant software

Sozi version: 21.02.21-1613918986
Drawing software I use: Inkscape 1.1 (1:1.1+202105261517+ce6663b3b7)
OS: Ubuntu 20.04.2 LTS
This happens in both Chrome and Firefox

### Steps to reproduce the problem

I set the aspect ration to 16:9 and generate the HTML output.

### Expected behavior

The HTML output should bi fitted to the screen without padding.

### Observed behavior

There's some padding at the left and top (This is a screenshot of the left top corner, the white section is unwanted):

![image](https://user-images.githubusercontent.com/16105138/121988540-daf6b580-cddd-11eb-9f30-6eeb4763bf75.png)

**Comment by tshoppa** [comment]
I cannot reproduce the behavior with Sozi 21.02/Inkscape 1.1 (I'm on win10, though).
Would it be possible to provide an example presentation?

**Comment by sina-mansour** [comment]
Sorry for the late reply, I must have missed the notification.

This is an example slide that you can check to see this effect:

https://sina-mansour.github.io/OHBM_2021_presentation

I tested this on both chrome and firefox (running on Ubuntu) and an unwanted white frame gets added to the slide.

**Comment by aumouvantsillage** [comment]
@sina-mansour Thanks for the example.

When rendering your document, the web browser does not ignore the whitespace between `<body>` and `<svg ...>` at the beginning of your document. Removing the spaces removes the padding.

It happens because your SVG contains `style` elements like this:

```html
<style id="style42643" type="text/css">
    *{stroke-linecap:butt;stroke-linejoin:round;white-space:pre;}
</style>
```

As a consequence, the `white-space:pre;` is applied to every element of the document, including the HTML `body`.

As a fix, I can add `white-space: normal;` to the `body` rule in the first `style` element of the document.
This fix is available in the next release. In the meantime, you can work around the issue by adding a custom stylesheet to your document with the following content:

```css
body {
    white-space: normal;
}
```

**Comment by aumouvantsillage** [comment]
As a side note, when playing your presentation, I observed that it is affected by issue #464 
The image is always blurry after each transition. Is it the same for you?

**Comment by sina-mansour** [comment]
Thank you for the solution, adding the extra style tag solved the issue for me.

Regarding the other issue, I usually use chrome and the slideshow renders correctly on chrome. But I agree that when I test it on firefox, after slide transition, the images all get blurred for some reason.
