### ISSUE TITLE
Sozi v21.12 does not save the presentation anymore as html

### ISSUE THREAD

**Issue by lopippo** [sozi-projects/Sozi#580]
Greetings, 

I do not know how to reopen a closed issue. I have commented on this apparent bug at #573.
Thank you for your patience!

Sincerely,
Filippo

**Comment by aumouvantsillage** [comment]
> I do not know how to reopen a closed issue

Maybe you can't.
But since this is a different problem, it makes sense to open a separate issue.

I confirm that the latest release no longer saves the HTML when the saving mode is set to "Manual". Sorry for the inconvenience.
I will replace the latest release 21.12 with a fixed release as soon as I can.

**Comment by lopippo** [comment]
Ah! right, so it was not me :-) I finally tried loading the presentation with version 21.11.14 with the intention of having it saved and it worked !

**Comment by aumouvantsillage** [comment]
Please try [Sozi 21.12.06](https://github.com/sozi-projects/Sozi/releases/tag/v21.12.06) and tell me if it works better for you.

**Comment by lopippo** [comment]
Greetings,

thank you for this quick release. Yes! you could :-) It works fine.
Thank you for your hard work on this exciting software!
Feel free to close this issue, then.

Sincerely,
Filippo
